#!/usr/bin/fish
make defconfig ARCH=aarch64
make ACCEL=n ARCH=aarch64 LOG=debug VM_CONFIGS=configs/vms/arceos-aarch64.toml FEATURES=hv,irq,fs APP_FEATURES=fs MEM=4G  run


# x86_64
# make ACCEL=y ARCH=x86_64 LOG=info VM_CONFIGS=configs/vms/arceos-x86_64.toml FEATURES=page-alloc-64g APP_FEATURES=fs run